version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    restart: always

  db:
    image: postgres
    environment:
      - POSTGRES_USER=nerdguardian
      - POSTGRES_PASSWORD=WFPZbVhdDQAtazQc78Rj
      - POSTGRES_DB=nerdguardian
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nerdguardian"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: