version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    restart: always

  db:
    image: postgres
    environment:
      - POSTGRES_USER=navycord
      - POSTGRES_PASSWORD=WFPZbVhdDQAtazQc78Rj
      - POSTGRES_DB=navycord
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U navycord"]
      interval: 5s
      timeout: 5s
      retries: 5