version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=navycord
      - POSTGRES_PASSWORD=WFPZbVhdDQAtazQc78Rj
      - POSTGRES_DB=navycord